### ISSUE TITLE
Optional cropping features

### ISSUE THREAD

**Issue by jimhare** [flokosiol/kirby-focus#10]
Hi Flo. Thanks for a really great plugin.
Could this be adapted into a crop field without too much trouble? Would be a lifesaver :)

It would save two coordinate-pairs instead of one, and have accompanying methods to perform the crop. Maybe, it could be one plugin with both features available… First you choose your focal point,  then you drag around a crop box (which is only permitted to contain the focal point within its bounds). The crop box ratio could be specified as an option.

What do you think?

**Comment by flokosiol** [comment]
Hi Jim.

Thanks for your feedback and your suggestion. To be honest, I won't extend the plugin in this way.  I had really bad experience with third party „rectangle-cropping-plugins“ for Drupal. So I decided to keep the Kirby plugin as simple and robust as possible.

If you are looking for a full cropping tool, please have a look at https://github.com/blankogmbh/kirby-cropper

I hope you can understand this 😄 
Regards, Flo.

**Comment by jimhare** [comment]
Totally understand; thanks for your reply! I'll fork anyway and give it a go myself. P.S. I tried blankogmbh's field first but it relies on Imagick which I don't have in MAMP :(
Thanks again. Jim
