### ISSUE TITLE
Forced focus idea

### ISSUE THREAD

**Issue by jenstornell** [flokosiol/kirby-focus#14]
I've got a new idea.

Maybe we sometimes need all the images to have a focus point on top center position, like this:

```php
echo $image->focusCrop(300,200, array('top' => 0, 'left' => 'center'));
```

The above could force the image position on top 0 and calculated center. It would be perfect for screenshots where we don't want to spend the time to manually set the focus points.

In the future I even hope it will reach the core but it seems to take time:
https://github.com/getkirby/toolkit/issues/99

What do you think?

**Comment by flokosiol** [comment]
I like that idea. But I think we should use `x` and `y` and percentage values to force a focus point like this …

```php
echo $image->focusCrop(300,200, array('x' => 0, 'y' => 50));
```

**Comment by jenstornell** [comment]
I agree. The we don't mix strings and integet. x and y is fine by me as well. =)

**Comment by jenstornell** [comment]
I could not wait for it so I created this:

https://github.com/jenstornell/kirby-crop-top

**Comment by flokosiol** [comment]
Alright. 👍 

I don't have much spare time at so moment, so I couldn't implement your suggestion so far. Sorry for that …
