### ISSUE TITLE
"Auto" values?

### ISSUE THREAD

**Issue by Andi-Lo** [flokosiol/kirby-focus#17]
Currently you have to specify 2 parameters (height and width) in order to generate a thumbnail with focusCrop.

In kirby you can do something like: `echo thumb($image, array('width' => 1920))` and kirby will take the image ratio into account and calculate the proper height.

With focus crop you can just do this: `echo $image->focusCrop(200);` which will crop a square. Is there a possibility to get something like `focusCrop(200, auto)` ? For me I almost always just use the width parameter for my thumbnail generations without a height so I can't use your plugin then in those cases.

**Comment by flokosiol** [comment]
Thanks for your suggestion. Maybe I'm wrong, but …

If you create thumbnails by defining either width or height and calculating the other value taking the ratio of the original image into account, then there's no cropping – you just scale the image. And if you don't crop the image, you don't need to define a focus point. In this case I would simply stick to the `thumb()` method as you described. 

But maybe you mean something different and I don't understand your use case. I would like to hear your feedback. 

Thanks and regards. 
Flo.

**Comment by Andi-Lo** [comment]
Ouh I never thought it that way. Seems you're right and it doesn't make sense with `auto` as an argument :)
