### ISSUE TITLE
focus y is set to x

### ISSUE THREAD

**Issue by heroheman** [flokosiol/kirby-focus#19]
Hi @flokosiol ! 
Your last commit broke something. 
Please have a look at: 
https://github.com/flokosiol/kirby-focus/blob/master/methods/file.php#L69

**The last argument should be a `y` not `x`.** 
This leads to incorrect behavior as it only reads the width, not the height. 

btw. I really like your plugin, keep up the good work.

**Comment by flokosiol** [comment]
Ouch. Looks like a copy/paste issue … but should be fixed now.
Thanks for reporting.
