### ISSUE TITLE
Images being stretched

### ISSUE THREAD

**Issue by medienbaecker** [flokosiol/kirby-focus#2]
Some image ratios seem to be stretched.

### Input images: 

![test1](https://cloud.githubusercontent.com/assets/7975568/15669816/77d6969e-2722-11e6-9c94-b2fa40633e40.jpg)
2800 x 1300

![test2](https://cloud.githubusercontent.com/assets/7975568/15669815/77d4f3f2-2722-11e6-9ce4-498ad3f1891b.jpg)
1766 x 1300

![test3](https://cloud.githubusercontent.com/assets/7975568/15669818/77de95a6-2722-11e6-844f-faab49127461.jpg)
1300 x 1300

![test4](https://cloud.githubusercontent.com/assets/7975568/15669817/77d8d7d8-2722-11e6-93c0-3caf533a2669.jpg)
869 x 1300

### Output images with 1440x650:

![test1-1440x650-50-50](https://cloud.githubusercontent.com/assets/7975568/15669822/823a9ffe-2722-11e6-8da6-18a3b8a531de.jpg)
Original: 2800 x 1300

![test2-1440x650-50-50](https://cloud.githubusercontent.com/assets/7975568/15669823/823ad442-2722-11e6-9792-ea0f0fa93090.jpg)
Original: 1766 x 1300

![test3-1440x650-50-50](https://cloud.githubusercontent.com/assets/7975568/15669824/823f950e-2722-11e6-967d-a35b1625396a.jpg)
Original: 1300 x 1300

![test4-1440x650-50-50](https://cloud.githubusercontent.com/assets/7975568/15669821/823a141c-2722-11e6-9c20-f0ab540c1ab5.jpg)
Original: 869 x 1300

Can you reproduce this with the images or is my configuration wrong?
It seems like only square input images are cropped correctly.

**Maybe** it has something to do with these lines, but I can't figure it out: https://github.com/flokosiol/kirby-focus/blob/master/focus.php#L88-L126

**Comment by medienbaecker** [comment]
Ok, I managed to find out what's wrong with the output images. The image height is correct, it's 650px in the example, but the actual height is the width: 1440px. I stretched the original image in Photoshop and the circle is exactly the same.

So it seems like the script always does the "square" cropping. Maybe it's this line: https://github.com/flokosiol/kirby-focus/blob/master/focus.php#L29

**Comment by medienbaecker** [comment]
I downloaded a pure Kirby 2.3 Starterkit, installed the focus plugin and tested it locally and on my server. Same thing:

![bildschirmfoto 2016-05-31 um 16 01 54](https://cloud.githubusercontent.com/assets/7975568/15677100/0d0585f6-2749-11e6-9408-8cd7d5ebe7c0.png)

**Comment by flokosiol** [comment]
I will have a look at this, thanks for reporting.
Did you implement the `focusCrop` method with one argument like this
```
<?php echo $image->focusCrop(200); ?>
```
or with two arguments like this
```
<?php echo $image->focusCrop(300,200); ?>
```

I guess I have to test some more edge cases (thumb height and/or width bigger than original, …)

**Comment by medienbaecker** [comment]
I tried both. If I crop a 200x200 square by  `<?php echo $image->focusCrop(200); ?>` there's still stretching.

Can you please test the images I uploaded in the first post in your installation? Maybe it's something else. It stretches almost every image in my installations. If the image doesn't contain a circle or text it's not immediately noticeable.

**Comment by flokosiol** [comment]
I think I found the problem, but I will do some more testing. If you can't wait for so long, you could you change this line …
https://github.com/flokosiol/kirby-focus/blob/master/focus.php#L132
```
$img->crop($x1, $y1, $x2, $y2)->resize($thumb->options['width'], $thumb->options['height']);
```
… to this …
```
$img->crop($x1, $y1, $x2, $y2)->thumbnail($thumb->options['width'], $thumb->options['height']);
```

Regards, 
Flo.

**Comment by medienbaecker** [comment]
Wow, thank you for the fast solution! ❤️
