### ISSUE TITLE
Websites using Kirby Focus

### ISSUE THREAD

**Issue by flokosiol** [flokosiol/kirby-focus#21]
Make a list of websites using Kirby Focus.

**Comment by flokosiol** [comment]
https://github.com/flokosiol/kirby-focus/wiki
To add your website to the list, you can comment this issue, make a pull request for the wiki or contact me in any otherway you like. Thanks!

**Comment by malvese** [comment]
https://inprincipo.com/
https://tedxsaclay.com/
