### ISSUE TITLE
prevent upscaling

### ISSUE THREAD

**Issue by movingwater** [flokosiol/kirby-focus#22]
Is there a way to disable upscaling? If I use
```php
->focusCrop(1200,600)
```
and if the image is just 800px width it blows it up to 1200px.

**Comment by flokosiol** [comment]
Thanks for your feedback. This should be possible and I'll check it out.

But what do you think should happen, if only one dimension (width **or** height) is larger than the original?

```php
// original 800px x 800px

->focusCrop(1200,600)
```

**Possible results**
1. Crop only the height: 800px x 600px
2. Crop to desired reatio: 800px x 400px
3. Don't crop at all: 800px x 800px

**Comment by movingwater** [comment]
I would prefer to crop to the desired ratio (2).

**Comment by SimonWpt** [comment]
Crop means crop, not CropAndScale. For this reason I would select 1 :)

**Comment by flokosiol** [comment]
I also prefer 1, but I will check how the Kirby `crop()` method handles this.

**Comment by flokosiol** [comment]
Alright, Kirby `crop()` makes an upscale to match the larger value and then crops the image to the final dimensions.

**Comment by flokosiol** [comment]
I came back this issue after quite a long time and I think I will stick to the current behavior, because it's the same way the Kirby `crop()` method works. Let's keep things consistent 😉
