### ISSUE TITLE
Missing ;

### ISSUE THREAD

**Issue by SimonWpt** [flokosiol/kirby-focus#23]
https://github.com/flokosiol/kirby-focus/blob/master/fields/focus/assets/css/focus.css#L2

**Comment by flokosiol** [comment]
Damn. Will fix it soon. Thanks for reporting.

**Comment by flokosiol** [comment]
I fixed it on the `development` branch and added a `config.php` option to go fullwidth again:

```php
c::set('focus.field.fullwidth', true);
```

Would be awesome, if you could test it before I merge it to the `master` branch, @SimonWpt.
