### ISSUE TITLE
Broken focus field for non image file types

### ISSUE THREAD

**Issue by mikewink** [flokosiol/kirby-focus#27]
Thank you very much for your field! It is a nice addition to the Kirby universe. 👍 

I wanted to ask if it is normal for non-image fields to show a broken focus field? Maybe we can hide the field based on the supported mime types?

**Comment by flokosiol** [comment]
Thanks for reporting. 

In previous versions there was a `$file->canHaveThumbs()` Kirby core method [which did the check](https://github.com/flokosiol/kirby-focus/blob/master/fields/focus/focus.php#L106), but it seems to be deprecated. I will push a fix to the `development` branch in a minute. Would be awesome, if you could check it!?

**Comment by flokosiol** [comment]
https://github.com/flokosiol/kirby-focus/archive/develop.zip

**Comment by flokosiol** [comment]
Great. Thanks for testing. I will try to release a new version as soon as possible.
