### ISSUE TITLE
[K-Next] Cropped image won't update when focus changes

### ISSUE THREAD

**Issue by gerricom** [flokosiol/kirby-focus#29]
Hey! First things first: Thank you very much for having a beta of your plugin for the upcoming Kirby version! I really appreciate it!

I'm trying your `k-next` branch with the latest nightly build of Kirby and my image won't update if I change the focus. I don't know, if I'm missing something here, but for the moment, I have to empty the corresponding media directory...

**Comment by flokosiol** [comment]
Thanks for your feedback. 

Could you please have a look at the generated image filenames in your media folder? They should include the x and y coordinates.

**Comment by flokosiol** [comment]
Unfortunately I have no access to my computer at the moment, so it‘s not possible for me to have a closer look at this. But for now, let’s check the code which is responsible for the creation of the filename. 

Here the coordinates are added to the thumb options:
https://github.com/flokosiol/kirby-focus/blob/k-next/config.php#L76

And this is the Filename `crop()` method in Kirby which adds it to the filename. It changed with the latest beta. In older versions it was not possible to pass custom crop positions to the method. 
https://github.com/k-next/kirby/blob/master/src/Cms/Filename.php#L177

Could you please verify that your code is up to date?

… and just for the record, I‘m pretty sure you are using `focusCrop()` in your template, right?

I will have a closer look at this next week.

**Comment by gerricom** [comment]
Okay - I'm very sorry. It seems, I mixed up the nightly builds and the latest beta. I fetched the latest beta and suddenly, all is good. Sorry!

**Comment by flokosiol** [comment]
No problem at all. Glad, that it works now.
