### ISSUE TITLE
[K-Next] Autoloading-Issues on linux

### ISSUE THREAD

**Issue by gerricom** [flokosiol/kirby-focus#30]
I'm sorry to bother you again. I just tried to use your plugin on a Kirby 3 installation on a linux machine and the autoloader was unable to load `core/focus.php`. After I changed the filename to `Focus.php` the problem was gone.

**Comment by flokosiol** [comment]
Thanks for reporting. I had no problems so far, because I‘m on MacOS which is case insensitive. I‘ll fix that. 

Don‘t hesitate to report more bugs, if you find them. I really appreciate it! Thanks for testing.
