### ISSUE TITLE
Doesn't work with Imagemagick thumb driver

### ISSUE THREAD

**Issue by tristantbg** [flokosiol/kirby-focus#35]
I got a 500 error :

```Call to undefined function dd()```

Maybe use `dump()`instead ?

**Comment by flokosiol** [comment]
Oh damn. That was just for testing purposes. Thanks for reporting. 

I removed the line completely. 

If you‘ve installed the plugin with composer you will need to wait some more time until I can rebuild the package for packagist. But for now you can delete the whole line and it will (hopefully) work again.
