### ISSUE TITLE
"help" option not being displayed

### ISSUE THREAD

**Issue by HimmelsW** [flokosiol/kirby-focus#38]
Hi,

thank You for the great plugin!
Unfortunately if I extend the focus field with the 'help' option, the help text is not being displayed, it's in the source code though (tested in Chrome v72).
It's not a big deal, I just thought I'd let You know.
Cris

**Comment by flokosiol** [comment]
Thanks for reporting, Cris. I‘m pretty sure it’s not a big deal to fix this.

**Comment by flokosiol** [comment]
I finally found the time to include your idea. Would be awesome if you could test the latest release (3.0.2). Thanks in advance.

**Comment by HimmelsW** [comment]
That was quick!
Thanks a lot, it works beautifully!
All the best!
