### ISSUE TITLE
Use thumb presets from site config

### ISSUE THREAD

**Issue by theWeird** [flokosiol/kirby-focus#41]
Instead of defining image options on every use, can this plugin work with default/named presets from the sites config.php?  
https://getkirby.com/docs/reference/system/options/thumbs

For Thumbnail definitions used in several places of the page it would be great to call the method with the name of a preset or without any parameter for default preset.

**Comment by flokosiol** [comment]
That‘s a really good idea. I will have a look at it.

It may be that we can‘t reuse existing thumb presets, but need to set new ones for `focusCrop`. But this would still be useful, I think.

**Comment by flokosiol** [comment]
It took some time, but I finally implemented presets. @theWeird, would be awesome if you could check out the [presets-branch](https://github.com/flokosiol/kirby-focus/tree/feature/presets) and test the new feature. Thanks in advance!

Please find the documentation here:  
https://github.com/flokosiol/kirby-focus/tree/feature/presets#presets
