### ISSUE TITLE
Move Darkroom type definition out of global scope

### ISSUE THREAD

**Issue by mullema** [flokosiol/kirby-focus#42]
Hi!
I am building a crop plugin by extending the Darkroom Classes as you do. But I struggled over your code [here](https://github.com/flokosiol/kirby-focus/blob/master/index.php#L14):
```
// index.php line 14
Kirby\Image\Darkroom::$types['gd'] = 'Flokosiol\Focus\GdLib';
Kirby\Image\Darkroom::$types['im'] = 'Flokosiol\Focus\ImageMagick';
```
You are forcing everyone to use your classes and you still allow them to be overwritten by another plugin. If my plugin was loaded after yours, these two variables get overwritten by mine and your plugin does not work anymore in some cases. 

To avoid these sideeffects I suggest to move the two lines inside the `focusCrop` method.

**Comment by flokosiol** [comment]
Thanks for your suggestion. 

I thought it must be in global scope to replace the default Darkroom class. I will test it and fix it, if I find a better way …

**Comment by mullema** [comment]
They are two [properties in the Darkroom class](https://github.com/getkirby/kirby/blob/master/src/Image/Darkroom.php#L13). Whenever you call the [Darkroom::factory](https://github.com/getkirby/kirby/blob/master/src/Image/Darkroom.php#L25) it will return what is set in those properties. The only important thing is that you set **your** properties before your call Darkroom::factory. 
You are not doing that manually in your plugin, but it is called in the thumbs method. If you insert the property definition somewhere before you `return $this->thumb()` you will be fine.

**Comment by flokosiol** [comment]
Thanks for your help … very much appreciated!

**Comment by flokosiol** [comment]
I tried to implement your suggestion. Unfortunately, it doesn't work to set the Darkroom type definition inside the custom [focusCrop file method](https://github.com/flokosiol/kirby-focus/blob/master/index.php#L52).

However, it does work when I declare a [custom thumb component as you do](https://github.com/mullema/k3-image-clip/blob/master/components/thumb.php) like this …

<img width="880" alt="kirbyfocus-custom-thumb" src="https://user-images.githubusercontent.com/11918336/57165056-4cd63580-6df6-11e9-8618-e5e5494f73f5.png">

But as far as I can see, this will lead to conflicts with other custom thumb components because only one will finally be used by Kirby, right?

**Comment by mullema** [comment]
You are right, it does not work as I suggested. I don't quite understand why....
Unfortunately are thumbs components overwriting each other. The last one declared will be the one used. 

We could at least make our two plugins work together:
- You omit using the thumbs component.
- You declare your Darkroom::$types globally (as before).
- I reset the Darkroom::$types after cliping in my plugin.

But that does not save you from other plugins messing with Darkroom::$types, I don't see a good solution for this problem.

**Comment by mullema** [comment]
I just understood why...
focusCrop is called on a Kirby instance, then file::version and the job file is generated (the thumbs component is never called here). 
To actually generate the thumb, it is a new request to the server (the image url), a new Kirby instance, which does never go via focusCrop but directly to the thumbs component.

**Comment by flokosiol** [comment]
Ok, I got it. Thanks for taking the time and for this explanation.

**Comment by mullema** [comment]
I posted a possible solution in the ideas repo. please upvote! https://github.com/getkirby/ideas/issues/278
