### ISSUE TITLE
Plugin not loading?

### ISSUE THREAD

**Issue by ceesvanegmond** [flokosiol/kirby-focus#44]
I followed the install guide for this plugin. In my blueprint I can add the `focus` field type. No errors so ar. But when I load the webpage, I only get a white space. No errors at all.
I'm using the kirby content builder, but without this it also doesn't work.
Used several install methods, none of seem to work. Kirby version: 3.1.3

Do I 
![Schermafbeelding 2019-05-21 om 17 02 41](https://user-images.githubusercontent.com/883497/58107672-9a221780-7bea-11e9-8228-8fd7a9b1af72.png)
miss something?

**Comment by flokosiol** [comment]
Seems like you've added the field to a page blueprint, but it is only available for [file blueprints](https://getkirby.com/docs/reference/panel/blueprints/file).

I hope this solves the problem – if not, don't hesitate to get in touch again. I'm pretty sure we will find a solution 😉

**Comment by ceesvanegmond** [comment]
@flokosiol Ah, you're so right. How stupid... Works perfect! Thanks!

**Comment by flokosiol** [comment]
No problem, glad it works now. 

Maybe I should try to return a message if the field is used outside of a file context. This would be helpful, I guess.
