### ISSUE TITLE
resize broken after editing focus slightly

### ISSUE THREAD

**Issue by carstengrimm** [flokosiol/kirby-focus#45]
I am trying to add some sort of watermarking method to FocusCrop and GDlib to have a flexible way of creating automated watermarked images when using certain commands, i have had my attempt which seems to create the watermarked images as intended, however it seems like once i changed the code, kirby's $image->resize() function does not seem to work anymore.

so i am wondering if i am missing out on a few lines of code which potentially break something..

```
// GDLib
$image = $this->overlay($image, $options); // this i put below all other options e.g. blur,grayscale at about line 30

// later in the file

    protected function overlay(SimpleImage $image, array $options)
    {
        if($options['overlay'] === false){
            return $image;
        }
        return $image->overlay(kirby()->root('assets').'/watermark.png','center',1,0,0);
    }
```
and within my template I am using
```
<?php echo $image->focusCrop($w,$h,['overlay' => 'yes'])->url() ?>
```
this seems to correctly do the job, but using the default $image->resize() command does not generate images anymore.

any idea?

**Comment by carstengrimm** [comment]
The Part where i set

```
         // this line below
         $image = $this->overlay($image, $options);

```
seems to break some things, even though the overlay method exists

**Comment by flokosiol** [comment]
I'm not sure if I could follow all of your explanations, but I think I got it 😉 

In `GdLib.php` of the Focus plugin you have this code (please see the comment inside):

```php
public function process(string $file, array $options = []): array
    {
        $options = $this->preprocess($file, $options);

        $originalImage = new Image($file);
        if ($dimensions = $originalImage->dimensions()) {
            $options['originalWidth'] = $dimensions->width();
            $options['originalHeight'] = $dimensions->height();
        }

        $image = new SimpleImage();
        $image->fromFile($file);

        $image = $this->autoOrient($image, $options);
        $image = $this->resize($image, $options);
        $image = $this->blur($image, $options);
        $image = $this->grayscale($image, $options);

        // you added this line, right?
        $image = $this->overlay($image, $options);

        $image->toFile($file, null, $options['quality']);

        return $options;
    }
```

I think the methods `autoOrient()`, `resize()`, `blur()` and `grayscale()` (which are listed below in the file) are just helper methods for the [SimpleImage class](https://github.com/getkirby/kirby/blob/master/vendor/claviska/simpleimage/src/claviska/SimpleImage.php). 

The method you added and the end of the file also refers to `SimpleImage` and I think the code breaks, because there's no `overlay()` method in the `SimpleImage` class.

```php
// you added this new method?!
protected function overlay(SimpleImage $image, array $options)
    {
        if($options['overlay'] === false){
            return $image;
        }
        // this refers to the SimpleImage class, I think …
        return $image->overlay(kirby()->root('assets').'/watermark.png','center',1,0,0);
    }
```

Unfortunately I'm not sure if I can help you with this … 😕

**Comment by carstengrimm** [comment]
is there not?

https://github.com/getkirby/kirby/blob/03d6e96aa27f631e5311cb6c2109e1510505cab7/vendor/claviska/simpleimage/src/claviska/SimpleImage.php#L688

**Comment by flokosiol** [comment]
🤦‍♂ Oh, you're right. I totally overlooked that. 🤔  Strange … I can't spot any other errors …

**Comment by flokosiol** [comment]
I close the issue because it is not related to the functionality of the plugin. Sorry, that I couldn't help you with your question.
