### ISSUE TITLE
focusCrop does not work with srcset

### ISSUE THREAD

**Issue by gearsdigital** [flokosiol/kirby-focus#46]
Not sure if this works as expected but I figured that  `focusCrop` does not work with `srcset`.

This works:
```php
<?php foreach ($page->children()->listed() as $member): ?>
    <?= $member->image()->focusCrop(300, 400)->url(); ?>
<?php endforeach ?>
```

This does not...
```php
<?php foreach ($page->children()->listed() as $member): ?>
    <?= $member->image()->focusCrop(300, 400)->srcset(); ?>
<?php endforeach ?>
```

This code is based on https://getkirby.com/docs/reference/panel/samples/team

**Comment by gearsdigital** [comment]
Nevermind. I better should've RTFM, right? https://github.com/flokosiol/kirby-focus#focus-and-srcset-becomes-focussrcset

![facepalm](https://user-images.githubusercontent.com/965069/71900017-39d1ed00-315d-11ea-9973-d4c77cb04e23.gif)

**Comment by flokosiol** [comment]
No problem. Thanks for using the plugin!
