### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by HashandSalt** [flokosiol/kirby-focus#47]
Plugin throws the following issue when using focusSrcset in a template or controller:

```
 Whoops \ Exception \ ErrorException (E_DEPRECATED)
Non-static method Flokosiol\Focus::focusSrcset() should not be called statically
```

The line in the plugin causing it is line 70:

```
        'focusSrcset' => function ($sizes = null) {
            return Flokosiol\Focus::focusSrcset($this, $sizes);
        },
```

Observed in Kirby 3.3.2 running on PHP 7.2

**Comment by flokosiol** [comment]
Thanks for reporting. Line 165 in `src/Focus.php` might cause this issue. Changing it to `public static function …` should do the trick. 

I’ve no access to my computer right now. Would you mind test it yourself?

**Comment by flokosiol** [comment]
Just found out, that I can edit on my phone. But I still need to create a new release. To be continued … :)

**Comment by HashandSalt** [comment]
Yes, the fix seems to work ok :) 👍

**Comment by flokosiol** [comment]
Perfect. Thanks for testing.

**Comment by flokosiol** [comment]
Created version 3.0.4 with the fix.
