### ISSUE TITLE
Presets also with focusSrcset()?

### ISSUE THREAD

**Issue by lucadorata** [flokosiol/kirby-focus#49]
Hi @flokosiol - first of all thanks for providing this plugin - 
Is there also a way to use presets with `focusSrcset()`, analog to:
```
<?= $image->focusPreset('square') ?>
<?= $image->focusPreset('rectangle') ?>
```
?
I need to ask, because it's not mentioned in the docs...

**Comment by flokosiol** [comment]
Hi @lucadorata 
I'm sorry, but this is not possible at the moment. But the following idea might work (**untested!**):

In your config.php as described [here](https://getkirby.com/docs/guide/configuration).
```
<?php
return [
    'debug'  => true,
    'mySrcsetPresetConfig' => [
        '800w' => [
            'width' => 800,
            'height' => 800,
        ],
        '1400w' => [
            'width' => 1400,
            'height' => 1400,
        ]
    ]
];
```

In your template, snippet, whatever …
```
<?php $myFocusSrcsetPreset = option('mySrcsetPresetConfig'); ?>
<img 
  src="<?= $image->focusCrop(1000, 1000)->url() ?>"
  srcset="<?= $image->focusSrcset($myFocusSrcsetPreset); ?>"
>
```

Would be awesome if you could drop me a line if this works for you.
Good luck 😉

**Comment by lucadorata** [comment]
Hi @flokosiol, 
just want to let you know, that your suggestion worked like a charm. I was able to access the thumbs options already configured in config.php.
I used this code:
```
      $preset = option('thumbs.presets');
      $srcset = option('thumbs.srcsets');
      $pV = $preset[$data->imagecrop()->value()];
      $sV = $srcset[$data->imagecrop()->value()];

      $items = $data->slides()->toStructure();
      foreach ($items as $item):

      if ($item->image()->isNotEmpty()):
        if ($data->imagecrop() != "default") {
          // cropped image
          $image = $item->image()->toFile()->focusCrop($pV['width'], $pV['height'], ['quality' => $pV['quality']]);
          $imagesrcset = $item->image()->toFile()->focusSrcset($sV);
```

**Comment by jonasfeige** [comment]
I need this functionality very often so I built my own `fcsSrcset` function. Not meant as a proper plugin, but maybe it can be helpful for someone.

It has some defaults based on my own needs and the Tailwind breakpoints. But you can also pass a custom width and height for the base (smallest) image. It also accepts an array of breakpoints with the expected screen width and a ratio that refers to how much bigger the iteration should be than the base (smallest) image.

[fcs-srcset](https://github.com/jonasfeige/fcs-srcset)

**Comment by flokosiol** [comment]
Thanks for sharing!
