### ISSUE TITLE
Bug: Breaks when media-Folder is at another place

### ISSUE THREAD

**Issue by andreasotto** [flokosiol/kirby-focus#52]
**Thank you very much for your excellent plugin!**

I have the media folder at another place:

```

echo (new Kirby([
    'roots' => [
        'media' => __DIR__ . '/files',
    ]
]))->render();

```

Images are linked to a `/media/..` location in the image preview page. It should be `/files/..` in my case.  As a result there are broken images in the panel. Afterwards the whole panel does not work any more because there seems to be files overwritten or deleted as a side effect. 

The problem occurs as soon as you set the focus point and save. Then, the preview image disappears. As a second side effect, the complete kirby panel does not work anymore. The browser page stays white and in the console you can see some 404 errors.

**Comment by flokosiol** [comment]
Thanks for reporting. I will have a look at this as soon as possible, but it may take some time because my spare time is limited at the moment. Thanks for your patience.

**Comment by flokosiol** [comment]
I tried your config with a fresh starterkit (Kirby 3.3.5) and could reproduce the error – but without the Focus plugin installed. So this one is not Focus related.

Nevertheless, this config seem to fix it:

```
$kirby = new Kirby([
    'roots' => [
        'media' => __DIR__ . '/files',
    ],
    'urls' => [
        'media' => url('files'),
    ],
]);

echo $kirby->render();
```

… as described by @pedroborges in this [forum answer](https://forum.getkirby.com/t/routing-to-media-content-instead-of-media-folder-structure/12978/2?u=flokosiol). 

I also found this [related Kirby issue](https://github.com/getkirby/kirby/issues/1494).

**Comment by andreasotto** [comment]
Oh - i'm sorry to lead you in the wrong direction. Thank you very much for clarify this so fast.

**Comment by flokosiol** [comment]
No problem at all. Don't hesitate to get in touch again, if you run into any other issues which might be Focus related.
