### ISSUE TITLE
Question regarding 'components.thumb'

### ISSUE THREAD

**Issue by S1SYPHOS** [flokosiol/kirby-focus#54]
Hey there,
I'm currently building a plugin using `colorist`, and so far everything works fine: except for replacing Kirby's `thumb` method. I see that you went that way once, but commented it all out, so here's my question: What's your experience with the matter, and why did you decide to "replace" `Darkroom::$types` instead of hooking into `thumb`?

Whatever I do, I can't return anything useful using the workflow described in the docs / you commented out ..

**Comment by flokosiol** [comment]
The problem is that overriding the `thumb` component will only work once and maybe collide with other plugins. Please find the whole story in issue #42.

Regards Flo.

**Comment by S1SYPHOS** [comment]
Thanks very much!
