### ISSUE TITLE
kirby3-colorist supports 'Focus'

### ISSUE THREAD

**Issue by S1SYPHOS** [flokosiol/kirby-focus#55]
Hey there,
I wrote an [alternative thumb driver](https://github.com/fundevogel/kirby3-colorist) using [`colorist`](https://github.com/joedrago/colorist). It is capable of image conversion to `AVIF`, `WebP` and some other formats, as well as resizing them etc. As I liked your `Focus` plugin, I added support for it.

Don't know if that's enough to be mentioned on your plugin's README, as it's not exactly an extension - but I'm planning to maintain compatibility :fox_face: 

Regarding `AVIF`, this will take time as Kirby currently [hardcodes image formats](https://github.com/getkirby/kirby/pull/2840) being `resizable` (for Nolt feedback, see [here](https://kirby.nolt.io/110)).

Cheers & thanks for your great plugin!
S1SYPHOS

**Comment by flokosiol** [comment]
That sounds amazing! I will add a link to your plugin to the Focus README.

**Comment by S1SYPHOS** [comment]
Thanks for your kind words & the support!

In the following days (and before telling people on the forum) I will add documentation - your plugin was inspiring, I must admit :bear: so .. stay tuned!

**Comment by flokosiol** [comment]
Done. Finally.

**Comment by S1SYPHOS** [comment]
Don't bother, these things take me way longer sometimes ;)
