### ISSUE TITLE
Does not create cropped images on server

### ISSUE THREAD

**Issue by trych** [flokosiol/kirby-focus#56]
Hi there,
I have the issue that locally my cropped images are created just fine, but when I transfer the site to my server (uberspace.de, CentOS 7, PHP 7.4), the cropped images do not get created and therefore seem to be missing from the page:

![20201005-142818_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/95079535-0b4a6800-0717-11eb-8a47-b7e582ac98e9.png)

It does create corresponding entries in the `.jobs` folder though:
![20201005-143211_Screenshot_ForkLift](https://user-images.githubusercontent.com/9803905/95079919-94fa3580-0717-11eb-887d-ac3de243436d.png)

So I am not quite sure what is going wrong. Any idea what is wrong and/or how I could debug this?

Thanks!

Edit: I just switched to regular crop for testing and figured out, that does not work either. So this might be a Kirby issue rather than an issue with the plugin. Will investigate further and close the issue in case I find out it is indeed Kirby's fault.

**Comment by flokosiol** [comment]
As you mentioned in your edit – I'm not sure if this is Focus related!? Converting the `.job` files to real image should be done by Kirby itself. 

Maybe the folder permissions aren't set correctly?!

**Comment by trych** [comment]
Don't think it could have anything to do with folder permissions, as resized (non-cropped) images are created just fine and written to the folder.

Yes, the more I am trying around, the more it seems like it is not Focus related. Will close this for now.
Sorry for the fuss!

**Comment by flokosiol** [comment]
Thanks for the feedback. Would be awesome if you could let me know what your solution was once the issue is fixed. I'll be switching from U6 to U7, too. Maybe it's helpful for me or for others! Thanks.

**Comment by trych** [comment]
Sorry, back to the previous state.

Turns out I messed up with my git syncing and I still had `focusCrop()` method in use in my code. When I sorted this out and switched to Kirby's regular crop it *did* work again.

Unfortunately this means that the Focus crop is broken for me somehow. Any ideas how I could go about debugging this? I double checked `gd` and it is enabled and working fine for the normal crop.

**Comment by trych** [comment]
Ok, it works now, also with the Focus crop. I have no idea what went wrong, I spent like half the day yesterday double checking that everything is correct on my side, but apparently I missed something. I did a clean git clone now onto the server and now when it generates the images, everything seems to work. Sorry again for the confusion. Hope this issue will be closed forever now. 😄
