### ISSUE TITLE
Crop doesn't respect image boundaries

### ISSUE THREAD

**Issue by malvese** [flokosiol/kirby-focus#6]
The crop doesn't seem to take image boundaries into account:
* If the focus point is very close to the border, the crop may include areas outside of the image, and create a black stripe:

![the-sea-400x300-5-44](https://cloud.githubusercontent.com/assets/193492/15713050/12465e74-2815-11e6-814f-4809cf6c63b9.jpg)
* The opposite happens when the crop is narrow, the crop doesn't always include the focus point when it is near the side. Here I think I should see the corner of the image, including the whole black bag at the bottom?
![focus](https://cloud.githubusercontent.com/assets/193492/15713221/c87b6856-2815-11e6-8182-4899feda4612.jpg)

**Comment by medienbaecker** [comment]
I think the second problem is a different issue. **Every** image's width gets scaled up a bit. I just noticed that in my installation. You wrote it only happens when the "crop is narrow", can you check if it happens with a different focus point too? If there's enough room considering the focus point, the image borders should be visible.

**Comment by medienbaecker** [comment]
We could do `$img->fit_to_height($thumb->options['height']);` and `$img->fit_to_width($thumb->options['width']);` for the two fitting modes. The $x1, $x2, $y1, $y2 need to be converted from the original image to the new dimensions.

Do you have an idea @flokosiol?

**Comment by medienbaecker** [comment]
Yeah, I think finally found the error. It's here:
https://github.com/flokosiol/kirby-focus/blob/master/focus.php#L91
...and here:
https://github.com/flokosiol/kirby-focus/blob/master/focus.php#L110

The dimension that's not fitting inside the cropped dimension is not calculated correctly.

It should be:

`$height = floor($dimensions->width() * $thumb->options['ratio']);`

and 

`$width  = $dimensions->height() / $thumb->options['ratio'];`
