### ISSUE TITLE
WebP Support

### ISSUE THREAD

**Issue by HashandSalt** [flokosiol/kirby-focus#60]
Are there any plans to update the plugin to support the native WebP and AVIF support in Kirby 3.6?

**Comment by flokosiol** [comment]
Yes. So far, I didn't have the time to check out 3.6 but I will definitely do so. Since the plugin only calculates coordinates and manipulates GD and IM cropping, it hopefully works out of the box or only needs minor modification.

**Comment by HashandSalt** [comment]
Great :)

I think it will need a small modification as you now tell srcset which filetypes you would like:

```
    $shotsrcset = $shot->srcset([
      ['width' => 640, 'format' => 'webp'],
      ['width' => 640, 'format' => 'jpg'],
      ['width' => 640, 'format' => 'avif']
    ]);
```

**Comment by renestalder** [comment]
I'm willing to pay/donate whoever can make AVIF/WebP support on Kirby 3.6 happen on this one. I feel I got the need for this plugin for the first time, but I already optimized everything on this certain website to show AVIF and WebP.

And it would probably take me much more time to figure out how to patch this.

**Comment by HashandSalt** [comment]
FocusCrop ultimatly uses the the thumb() method as far as i can see, and I can only see about 3 occorances of that in the plugin code. It's this same method that does the webP avif magic in K3.6. So i think really it just needs a small tweak to those three lines to add the extra options that generates the WebP/Avif

**Comment by HashandSalt** [comment]
The good news is that this works out of the box without any mods:

```
<?php
  // you need a Kirby image object like this
  $image = $page->images()->first();
  echo $image->focusCrop(1200, 600, ['quality' => 80, 'format' => 'avif']);
  echo $image->focusCrop(1200, 600, ['quality' => 80, 'format' => 'webp']);
  echo $image->focusCrop(1200, 600, ['quality' => 80, 'format' => 'jpeg']);
?>
```

**Comment by renestalder** [comment]
@HashandSalt So, wait, does it now work or does it not work? I'm a bit confused.

Does it work with all the methods to generate srcsets yet?

**Comment by HashandSalt** [comment]
@renestalder the focusCrop method works out of the box without any mods to the plugin. This works already because it already accepts an options arrary and passes it through to ->thumb().

The srcset feature will need a tweak as it needs to know the desired format.

**Comment by HashandSalt** [comment]
@renestalder to help out @flokosiol i added support for the format option on the srcSet. I have tested this as far as I can so hopefully it will fly now, but i cant promise :) There is a pending PR for it.

**Comment by flokosiol** [comment]
Thanks @HashandSalt for checking this out and for your PR as well. Highly appreciated!

But I think `focusScrset()` already supports WebP out of the box, because the the [default Kirby srcset() method](https://github.com/getkirby/kirby/blob/main/src/Cms/FileModifications.php#L130) has not been changed for 3.6 and so should `focusSrcset` neither.

I successfully tested the following code with Kirby 3.6.0 and the latest Focus plugin:

```
<img
  src="<?= $image->focusCrop(1000, 1000, ['format' => 'webp'])->url() ?>"
  srcset="<?=
    $image->focusSrcset([
      '800w' => [
        'width' => 800,
        'height' => 800,
        'format' => 'webp',
      ],
      '1400w' => [
        'width' => 1400,
        'height' => 1400,
        'format' => 'webp',
      ]
    ]);
  ?>"
>
```

@renestalder  Would be awesome, if you could check if this works for you, too.

**Comment by HashandSalt** [comment]
@flokosiol ahhhhh when i messing around with it today, i didnt think to put the format into each width array. I thought it was a seperate thing. Thats a better way, for sure.

**Comment by flokosiol** [comment]
Just for the record … I saw, that I didn't create a new release after introducing the focusSrcset presets in August. Totally unrelated to this issue, but I quickly caught up on that. At leaset, we got that fixed :) 

I'll close this one, but if you ran into any issues @renestalder – don't hesitate to re-open it.

And thanks again @HashandSalt for your commitment!

**Comment by renestalder** [comment]
Awesome folks, thanks. I will get that tested.
