### ISSUE TITLE
Kirby 3.5.x not supported in v3.0.8

### ISSUE THREAD

**Issue by thathoff** [flokosiol/kirby-focus#66]
The new version does not work with Kirby 3.5.0 anymore because the `F` helper class has been moved from `Kirby\Toolkit\F` to `Kirby\Filesystem\F`. The solution is to pin the plugin to version `3.0.7` 

Maybe you can add an info to the README or even include the requirement in the composer.json.

PS: Thanks for this great plugin 🚀

**Comment by owzim** [comment]
Oh no! @flokosiol please make it keep the 3.5 compatibility. We have multiple 3.5 installations and cannot update for now.

**Comment by flokosiol** [comment]
I'm sorry @owzim – this was not intended. 

I'll try to separate this. My plan is to release a 3.0.9 with the latest fixes compatible to K3.5 and a new 3.1 with all breaking changes from K3.6. This might be the best solution, right?

**Comment by flokosiol** [comment]
Sorry for the massive delay, but I was really busy the last month doing client work. 

I would like to solve #65 first, bevor creating a new version 3.1 for Kirby 3.6+

**Comment by flokosiol** [comment]
Hey folks, could you please check if the latest version of the new `kirby-3.5` branch works for you? 

https://github.com/flokosiol/kirby-focus/tree/kirby-3.5

I reverted the GD and IM Darkroom classes to the latest Kirby 3.5 version but tried to include the latest fix of #63 as well. It was a bit confusing to be honest. 😄 If everything is fine, I would release a new Focus version 3.0.9 for Kirby 3.5 (and 3.1 for Kirby 3.6 as well).

Thanks a lot for your support! ❤️

**Comment by thathoff** [comment]
Thank you. It seems to work fine!

**Comment by flokosiol** [comment]
Great, thanks for the quick reply.

**Comment by flokosiol** [comment]
I just released [3.0.9](https://github.com/flokosiol/kirby-focus/releases/tag/3.0.9) and hope I configured the version numbers and dependencies correctly.
