### ISSUE TITLE
CSS not being loaded

### ISSUE THREAD

**Issue by squareclouds** [flokosiol/kirby-focus#68]
hey everyone,

i am using the latest version of both plugin and kirby (kirby 3.6.2) and the plugin is working fine, but in the panel the css is not being loaded. for the time being i copied everything from the index.css into my custom-panel.css. i am also using the autofocus plugin (which also is working fine), but i think that might be irrelevant

any idea why this is happening?

**Comment by flokosiol** [comment]
I set up a fresh Kirby Starterkit (3.6.2) with the latest Focus plugin (3.0.8) and everything seems fine. 

The styles are automatically included in `/media/plugins/index.css`. Could you please have a look if this file exists and if css selectors like `.kirby-focus-field .focus-box` are included? Kirby should take care of this.

<img width="1440" alt="kirby-3 6 2_focus-3 0 8" src="https://user-images.githubusercontent.com/11918336/156844653-1a623790-4385-4c66-8938-c53525d257f8.png">

**Comment by squareclouds** [comment]
strange, right now i:

- deleted the css code from my custom panel (i had copy pasted it in there as a workaround)
- tested like that and now it worked
- removed the link to the custom panel css from the config, just to check because i had done this after installing the plugin and it didnt work, i thought maybe loading the custom css was causing the problem
- and this time it worked as well

dont know what to tell you ^^ strange.... specially because i tested a couple of combinations. we can close this now then :) thank you!
