### ISSUE TITLE
Optional color fading ?

### ISSUE THREAD

**Issue by plagasul** [flokosiol/kirby-focus#71]
Great plugin! thank you!

The field shows a  B&W version of the image, and only color on hover.

It is a cool effect, but mildly confusing for some clients.

Is it possible to deactivate this feature ?

Thank you

**Comment by flokosiol** [comment]
Thanks for your comment. Do you know about the possibility to customize the panel via your own css file?

https://getkirby.com/docs/cookbook/panel/customizing-panel

I think this is the best way to change the style of the focus field and adapt it to your needs.

**Comment by plagasul** [comment]
Understood, thank you.
