### ISSUE TITLE
Correct URL to "Setting a focus point" in readme

### ISSUE THREAD

**Issue by matthacksteiner** [flokosiol/kirby-focus#76]
Kirby changed their Documentation Url scheme.

The old link to the "official Kirby feature page" does not work any more:
https://getkirby.com/docs/guide/files/files#setting-a-focus-point

New link:
https://getkirby.com/docs/guide/files#setting-a-focus-point

**Comment by flokosiol** [comment]
Thanks for reporting @matthacksteiner! I fixed the link in the readme file.
