### ISSUE TITLE
Some file names do not work

### ISSUE THREAD

**Issue by danst0** [flokosiol/kirby-focus#8]
Some file names do not seem to work and no target setting picture is shown. 
E.g. Photo%20Juni%2025%2C%2010%2046%2039.jpeg
Might be related to spaces. 

Daniel

**Comment by flokosiol** [comment]
Thanks for reporting. I will have a look at this.

**Comment by flokosiol** [comment]
I found the problem. There will be a fix soon – maybe today 😉
