### ISSUE TITLE
It's moving on save

### ISSUE THREAD

**Issue by jenstornell** [flokosiol/kirby-focus#9]
When I click save the focus point moves a few pixels. It's probably not a problem for me right now but I wanted you to know.

Watch carefully and you will probably see it:

![point](https://cloud.githubusercontent.com/assets/927011/17293549/3355e0d8-57f1-11e6-8aa3-3d125d3f43c1.gif)

I guess I'm using it with GD. At least I don't have ImageMagic installed.

**Comment by flokosiol** [comment]
Thanks for reporting, Jens. This could be a rounding issue. I will have a closer look at it.

**Comment by flokosiol** [comment]
Hi Jens,
would be great if you could have short look at the develop branch. I think I fixed the issue, but someone else checking it would be awesome. Thanks in advance.

Flo.

**Comment by flokosiol** [comment]
By the way: The problem was that the positioning on click was made by using px values, but the positioning after a page reload was made by % values. So it was indeed a kind of rounding issue – as I suspected. I simply changed everything to %.

**Comment by jenstornell** [comment]
It works for me as well! :)
